import React, { useState, useMemo } from 'react';
import { PackageItem, Customer } from '../../types';
import { StorageService } from '../../services/storage';
import { useStorageCollections } from '../../hooks/useStorageCollection';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';
import {
  Wifi,
  Plus,
  Zap,
  Check,
  Edit2,
  Users,
  DollarSign,
  Trophy,
  Award,
  Sparkles,
  Receipt,
  CheckCircle2,
  AlertCircle,
  FileText,
  BarChart3,
  Search,
  Activity,
  Layers,
} from 'lucide-react';
import { Modal } from '../common/Modal';

export const PackagesView: React.FC = () => {
  const { user } = useAuth();
  const { showToast } = useToast();

  const [{ packages, customers, invoices }] = useStorageCollections({
    packages: () => StorageService.getPackages(),
    customers: () => StorageService.getCustomers(),
    invoices: () => StorageService.getInvoices(),
  });
  const [search, setSearch] = useState('');
  const [viewMode, setViewMode] = useState<'cards' | 'table'>('cards');
  const [selectedPkgForReport, setSelectedPkgForReport] = useState<PackageItem | null>(null);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingPkg, setEditingPkg] = useState<PackageItem | null>(null);

  const [name, setName] = useState('');
  const [speedMbps, setSpeedMbps] = useState(25);
  const [price, setPrice] = useState(2500);
  const [type, setType] = useState<'Fiber' | 'Wireless' | 'Cable'>('Fiber');
  const [desc, setDesc] = useState('');

  const openAdd = () => {
    setEditingPkg(null);
    setName('');
    setSpeedMbps(30);
    setPrice(3000);
    setType('Fiber');
    setDesc('Unlimited CIR fiber bandwidth with ultra low latency');
    setIsModalOpen(true);
  };

  const openEdit = (pkg: PackageItem) => {
    setEditingPkg(pkg);
    setName(pkg.name);
    setSpeedMbps(pkg.speedMbps || parseInt(pkg.speed) || 20);
    setPrice(pkg.price);
    setType(pkg.type || 'Fiber');
    setDesc(pkg.description || '');
    setIsModalOpen(true);
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;

    if (editingPkg) {
      const updated: PackageItem = {
        ...editingPkg,
        name,
        speed: `${speedMbps} Mbps`,
        speedMbps: Number(speedMbps),
        price: Number(price),
        type,
        description: desc,
      };
      StorageService.savePackage(updated, user?.email);
      showToast('success', 'Package Updated', `${name} plan updated.`);
    } else {
      const newPkg: PackageItem = {
        id: `pkg-${Date.now()}`,
        name,
        speed: `${speedMbps} Mbps`,
        speedMbps: Number(speedMbps),
        price: Number(price),
        type,
        activeSubscribers: 0,
        description: desc,
      };
      StorageService.savePackage(newPkg, user?.email);
      showToast('success', 'Package Added', `${name} plan added to internet catalog.`);
    }

    setIsModalOpen(false);
  };

  // Comprehensive Package Financial & Intelligence Analytics
  const packageAnalytics = useMemo(() => {
    const totalNetworkSubscribers = customers.length || 1;

    const stats = packages.map((pkg) => {
      const pkgCusts = customers.filter((c) => c.packageId === pkg.id);
      const activeCount = pkgCusts.filter((c) => c.status === 'Active').length;
      const suspendedCount = pkgCusts.filter((c) => c.status === 'Suspended').length;

      const custIds = new Set(pkgCusts.map((c) => c.id));
      const pkgInvoices = invoices.filter((inv) => custIds.has(inv.customerId));

      const invBilled = pkgInvoices.reduce((sum, inv) => sum + (Number(inv.amount) || 0), 0);
      const invReceived = pkgInvoices
        .filter((inv) => inv.status === 'Paid')
        .reduce((sum, inv) => sum + (Number(inv.amount) || 0), 0);
      const invPending = pkgInvoices
        .filter((inv) => inv.status === 'Unpaid' || inv.status === 'Partial')
        .reduce((sum, inv) => sum + (Number(inv.amount) || 0), 0);

      const customerLedgerPending = pkgCusts.reduce((sum, c) => sum + (Number(c.pendingBalance) || 0), 0);
      const effectivePending = invPending > 0 ? invPending : customerLedgerPending;

      // Monthly recurring demand generated by this package
      const monthlyDemand = pkgCusts.reduce(
        (sum, c) => sum + (Number(c.totalMonthly || c.monthlyFee) || pkg.price),
        0
      );
      const effectiveBilled = invBilled > 0 ? invBilled : monthlyDemand;

      const recoveryRate =
        effectiveBilled > 0 ? Math.min(100, Math.round((invReceived / effectiveBilled) * 100)) : 0;

      const marketShare = Math.round((pkgCusts.length / totalNetworkSubscribers) * 100);

      return {
        pkg,
        customers: pkgCusts,
        invoices: pkgInvoices,
        totalCustomers: pkgCusts.length,
        activeCount,
        suspendedCount,
        monthlyDemand,
        totalBilled: effectiveBilled,
        totalReceived: invReceived,
        totalPending: effectivePending,
        recoveryRate,
        marketShare,
      };
    });

    // Rank by total customers and revenue
    const sorted = [...stats].sort(
      (a, b) => b.totalCustomers - a.totalCustomers || b.totalReceived - a.totalReceived
    );

    const rankedMap = new Map<string, number>();
    sorted.forEach((item, index) => {
      rankedMap.set(item.pkg.id, index + 1);
    });

    return stats.map((item) => ({
      ...item,
      rank: rankedMap.get(item.pkg.id) || 1,
      isTopSeller: rankedMap.get(item.pkg.id) === 1,
    }));
  }, [packages, customers, invoices]);

  // Overall totals across all packages
  const networkTotals = useMemo(() => {
    return packageAnalytics.reduce(
      (acc, curr) => ({
        subscribers: acc.subscribers + curr.totalCustomers,
        active: acc.active + curr.activeCount,
        suspended: acc.suspended + curr.suspendedCount,
        monthlyDemand: acc.monthlyDemand + curr.monthlyDemand,
        billed: acc.billed + curr.totalBilled,
        received: acc.received + curr.totalReceived,
        pending: acc.pending + curr.totalPending,
      }),
      { subscribers: 0, active: 0, suspended: 0, monthlyDemand: 0, billed: 0, received: 0, pending: 0 }
    );
  }, [packageAnalytics]);

  const topPackage = useMemo(() => {
    return packageAnalytics.find((p) => p.rank === 1);
  }, [packageAnalytics]);

  const filteredAnalytics = useMemo(() => {
    return packageAnalytics.filter(
      (item) =>
        item.pkg.name.toLowerCase().includes(search.toLowerCase()) ||
        (item.pkg.type || 'Fiber').toLowerCase().includes(search.toLowerCase()) ||
        item.pkg.speed.toLowerCase().includes(search.toLowerCase())
    );
  }, [packageAnalytics, search]);

  const selectedPkgData = useMemo(() => {
    if (!selectedPkgForReport) return null;
    return packageAnalytics.find((p) => p.pkg.id === selectedPkgForReport.id);
  }, [packageAnalytics, selectedPkgForReport]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-black text-white flex items-center gap-2">
            <Wifi className="w-6 h-6 text-cyan-400" />
            Internet Packages &amp; Tariff Intelligence Report
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Full comprehensive package reporting: subscribers, billed amount, collected revenue, pending dues, and popularity rankings
          </p>
        </div>

        <button
           type="button"
          onClick={openAdd}
          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-black text-xs shadow-lg shadow-cyan-950/40"
        >
          <Plus className="w-4 h-4" />
          + Add Package
        </button>
      </div>

      {/* Network KPI Summary Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3.5">
        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-lg">
          <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
            <Layers className="w-3.5 h-3.5 text-cyan-400" />
            Active Tariffs
          </span>
          <p className="text-2xl font-black text-white mt-1">{packages.length}</p>
          <span className="text-[10px] text-slate-500">Broadband Plans</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-lg">
          <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
            <Users className="w-3.5 h-3.5 text-blue-400" />
            Total Subscribed
          </span>
          <p className="text-2xl font-black text-white mt-1 font-mono">{networkTotals.subscribers}</p>
          <span className="text-[10px] text-emerald-400 font-medium">
            {networkTotals.active} Active | {networkTotals.suspended} Suspended
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 shadow-lg">
          <span className="text-[11px] text-slate-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
            <Receipt className="w-3.5 h-3.5 text-purple-400" />
            Monthly Demand
          </span>
          <p className="text-2xl font-black text-white mt-1 font-mono">
            Rs. {networkTotals.monthlyDemand.toLocaleString()}
          </p>
          <span className="text-[10px] text-slate-400">Total Monthly Recurring</span>
        </div>

        <div className="p-4 rounded-2xl bg-emerald-950/30 border border-emerald-800/60 shadow-lg">
          <span className="text-[11px] text-emerald-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
            Total Received (Paid)
          </span>
          <p className="text-2xl font-black text-emerald-300 mt-1 font-mono">
            Rs. {networkTotals.received.toLocaleString()}
          </p>
          <span className="text-[10px] text-emerald-400 font-bold">
            {networkTotals.billed > 0
              ? Math.round((networkTotals.received / networkTotals.billed) * 100)
              : 100}
            % Overall Recovery
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-rose-950/30 border border-rose-800/60 shadow-lg col-span-2 lg:col-span-1">
          <span className="text-[11px] text-rose-400 font-semibold uppercase tracking-wider flex items-center gap-1.5">
            <AlertCircle className="w-3.5 h-3.5 text-rose-400" />
            Total Pending Bills
          </span>
          <p className="text-2xl font-black text-rose-300 mt-1 font-mono">
            Rs. {networkTotals.pending.toLocaleString()}
          </p>
          <span className="text-[10px] text-rose-400 font-medium">Uncollected Balance</span>
        </div>
      </div>

      {/* Top Package Spotlight ("Konsa Agy Hy Dosroon Sy") */}
      {topPackage && (
        <div className="p-4 rounded-2xl bg-gradient-to-r from-amber-950/40 via-slate-900 to-cyan-950/40 border border-amber-500/40 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-center gap-3.5">
            <div className="w-12 h-12 rounded-2xl bg-amber-500/20 border border-amber-500/50 flex items-center justify-center text-amber-300 shadow-lg shadow-amber-950/50">
              <Trophy className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 text-[10px] font-black uppercase tracking-wider flex items-center gap-1">
                  <Sparkles className="w-3 h-3" /> #1 Most Popular Package
                </span>
                <span className="text-xs text-slate-400 font-mono">Highest Market Adoption</span>
              </div>
              <h3 className="text-lg font-black text-white mt-0.5">
                {topPackage.pkg.name} — {topPackage.pkg.speed} (Rs. {topPackage.pkg.price.toLocaleString()}/mo)
              </h3>
              <p className="text-xs text-slate-300">
                Leading with <span className="text-amber-300 font-bold">{topPackage.totalCustomers} Subscribers</span> ({topPackage.marketShare}% of network), generating{' '}
                <span className="text-emerald-400 font-bold font-mono">Rs. {topPackage.totalReceived.toLocaleString()} in revenue</span>.
              </p>
            </div>
          </div>

          <button
             type="button"
            onClick={() => setSelectedPkgForReport(topPackage.pkg)}
            className="px-4 py-2 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 font-bold text-xs flex items-center gap-1.5 transition-all self-end md:self-auto"
          >
            <BarChart3 className="w-4 h-4" />
            View Package Dossier
          </button>
        </div>
      )}

      {/* Filter and View Toggle Toolbar */}
      <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
        <div className="relative w-full max-w-sm">
          <Search className="w-4 h-4 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search plans, speeds, fiber/wireless..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-9 pr-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400"
          />
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto justify-between sm:justify-end">
          <span className="text-slate-400 font-semibold">{filteredAnalytics.length} Packages</span>
          <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800">
            <button
               type="button"
              onClick={() => setViewMode('cards')}
              className={`px-3 py-1.5 rounded-lg font-bold text-xs transition-colors ${
                viewMode === 'cards'
                  ? 'bg-blue-600 text-white shadow'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Cards
            </button>
            <button
               type="button"
              onClick={() => setViewMode('table')}
              className={`px-3 py-1.5 rounded-lg font-bold text-xs transition-colors ${
                viewMode === 'table'
                  ? 'bg-blue-600 text-white shadow'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Audit Table
            </button>
          </div>
        </div>
      </div>

      {/* Cards View */}
      {viewMode === 'cards' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {filteredAnalytics.map((item) => {
            const { pkg, rank, isTopSeller, totalCustomers, activeCount, suspendedCount, totalBilled, totalReceived, totalPending, recoveryRate, marketShare } = item;

            return (
              <div
                key={pkg.id}
                className={`p-6 rounded-3xl bg-slate-900 border transition-all shadow-xl flex flex-col justify-between group relative ${
                  isTopSeller
                    ? 'border-amber-500/60 shadow-amber-950/20'
                    : rank === 2
                    ? 'border-slate-600'
                    : rank === 3
                    ? 'border-amber-800/60'
                    : 'border-slate-800 hover:border-cyan-800/80'
                }`}
              >
                <div>
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-300 border border-cyan-800 uppercase font-bold">
                        {pkg.type} FTTH
                      </span>
                      {isTopSeller ? (
                        <span className="px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/40 text-[10px] font-black uppercase flex items-center gap-1">
                          <Trophy className="w-3 h-3 text-amber-400" /> #1 Best Seller
                        </span>
                      ) : (
                        <span className="px-2 py-0.5 rounded-full bg-slate-950 text-slate-400 border border-slate-800 text-[10px] font-semibold">
                          Rank #{rank}
                        </span>
                      )}
                    </div>
                    <button
                       type="button"
                      onClick={() => openEdit(pkg)}
                      className="text-slate-500 hover:text-cyan-400 p-1 rounded hover:bg-slate-800"
                      title="Edit package"
                    >
                      <Edit2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <h3 className="text-xl font-black text-white mt-3 group-hover:text-cyan-300 transition-colors">
                    {pkg.name}
                  </h3>
                  <p className="text-xs text-slate-400 mt-1 leading-relaxed line-clamp-2">
                    {pkg.description || 'Dedicated symmetric fiber internet bandwidth with high uptime SLA.'}
                  </p>

                  <div className="mt-4 flex items-baseline justify-between">
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-black text-white">{pkg.speedMbps}</span>
                      <span className="text-xs font-extrabold text-cyan-400">Mbps</span>
                    </div>

                    <div className="text-right">
                      <span className="text-xs font-semibold text-slate-400">PKR </span>
                      <span className="text-xl font-black text-white font-mono">
                        {pkg.price.toLocaleString()}
                      </span>
                      <span className="text-[11px] text-slate-400">/mo</span>
                    </div>
                  </div>

                  {/* Financial Overview Metrics */}
                  <div className="mt-4 grid grid-cols-3 gap-2 text-xs">
                    <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">
                      <span className="text-[10px] text-slate-400 uppercase font-semibold block">Total Billed</span>
                      <p className="font-mono font-bold text-white text-xs mt-0.5 truncate">
                        Rs. {totalBilled.toLocaleString()}
                      </p>
                    </div>

                    <div className="p-2 rounded-xl bg-emerald-950/40 border border-emerald-800/60">
                      <span className="text-[10px] text-emerald-400 uppercase font-semibold block">Received</span>
                      <p className="font-mono font-black text-emerald-300 text-xs mt-0.5 truncate">
                        Rs. {totalReceived.toLocaleString()}
                      </p>
                    </div>

                    <div className="p-2 rounded-xl bg-rose-950/40 border border-rose-800/60">
                      <span className="text-[10px] text-rose-400 uppercase font-semibold block">Pending</span>
                      <p className="font-mono font-bold text-rose-300 text-xs mt-0.5 truncate">
                        Rs. {totalPending.toLocaleString()}
                      </p>
                    </div>
                  </div>

                  {/* Subscribers & Market Share */}
                  <div className="mt-3 pt-3 border-t border-slate-800 flex items-center justify-between text-xs">
                    <span className="text-slate-400 flex items-center gap-1 font-semibold">
                      <Users className="w-3.5 h-3.5 text-cyan-400" /> Subscribers:
                    </span>
                    <span className="font-extrabold text-cyan-300 font-mono">
                      {totalCustomers} Users{' '}
                      <span className="text-[10px] text-slate-400 font-normal">({marketShare}% share)</span>
                    </span>
                  </div>
                </div>

                <button
                   type="button"
                  onClick={() => setSelectedPkgForReport(pkg)}
                  className="mt-4 w-full py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white font-bold text-xs flex items-center justify-center gap-1.5 transition-colors border border-slate-700"
                >
                  <FileText className="w-3.5 h-3.5 text-cyan-400" />
                  View Package Report
                </button>
              </div>
            );
          })}
        </div>
      ) : (
        /* Audit Table View */
        <div className="rounded-2xl bg-slate-900 border border-slate-800 overflow-hidden shadow-xl">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-950 text-slate-400 uppercase text-[10px] tracking-wider border-b border-slate-800">
                <tr>
                  <th className="px-4 py-3">Rank &amp; Package</th>
                  <th className="px-4 py-3">Bandwidth Speed</th>
                  <th className="px-4 py-3 text-right">Tariff (PKR)</th>
                  <th className="px-4 py-3 text-center">Subscribers</th>
                  <th className="px-4 py-3 text-right">Monthly Demand</th>
                  <th className="px-4 py-3 text-right">Received (Paid)</th>
                  <th className="px-4 py-3 text-right">Pending Balance</th>
                  <th className="px-4 py-3 text-center">Recovery %</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 font-mono">
                {filteredAnalytics.map((item) => (
                  <tr key={item.pkg.id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="px-4 py-3 font-sans">
                      <div className="flex items-center gap-2">
                        {item.isTopSeller ? (
                          <span className="w-6 h-6 rounded-full bg-amber-500/20 text-amber-300 font-bold flex items-center justify-center text-xs">
                            🥇
                          </span>
                        ) : (
                          <span className="w-6 h-6 rounded-full bg-slate-800 text-slate-300 font-bold flex items-center justify-center text-xs">
                            #{item.rank}
                          </span>
                        )}
                        <span className="font-bold text-white">{item.pkg.name}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-cyan-300 font-bold">{item.pkg.speed}</td>
                    <td className="px-4 py-3 text-right font-bold text-white">
                      Rs. {item.pkg.price.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-center font-bold text-white">
                      {item.totalCustomers}{' '}
                      <span className="text-[10px] text-emerald-400 font-normal">({item.activeCount} active)</span>
                    </td>
                    <td className="px-4 py-3 text-right font-bold text-slate-200">
                      Rs. {item.monthlyDemand.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right font-bold text-emerald-400">
                      Rs. {item.totalReceived.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right font-bold text-rose-400">
                      Rs. {item.totalPending.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-center font-bold">
                      <span
                        className={`px-2 py-0.5 rounded-full text-[11px] ${
                          item.recoveryRate >= 80
                            ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                            : 'bg-amber-950 text-amber-400 border border-amber-800'
                        }`}
                      >
                        {item.recoveryRate}%
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right font-sans">
                      <button
                         type="button"
                        onClick={() => setSelectedPkgForReport(item.pkg)}
                        className="px-3 py-1 rounded-lg bg-cyan-500/20 text-cyan-300 hover:bg-cyan-500/30 text-xs font-bold"
                      >
                        Report
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* PACKAGE REPORT DOSSIER MODAL */}
      {selectedPkgData && (
        <Modal
          isOpen
          onClose={() => setSelectedPkgForReport(null)}
          title={`${selectedPkgData.pkg.name} — Comprehensive Plan Report`}
          description={`Speed: ${selectedPkgData.pkg.speed} | Base Tariff: Rs. ${selectedPkgData.pkg.price.toLocaleString()}/month | Medium: ${selectedPkgData.pkg.type} FTTH`}
          size="lg"
          footer={
            <button
              type="button"
              onClick={() => setSelectedPkgForReport(null)}
              className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs"
            >
              Close Report
            </button>
          }
        >
          <div className="space-y-6">
            <div>
              <div className="flex items-center gap-2">
                <span className="px-2.5 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 text-xs font-bold border border-cyan-500/40">
                  Tariff Intelligence Dossier
                </span>
                <span className="text-xs text-slate-400 font-mono">
                  Rank #{selectedPkgData.rank} of {packages.length} Packages
                </span>
              </div>
            </div>

            {/* 4 Financial Highlight Cards */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
              <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-[10px] text-slate-400 uppercase font-semibold font-sans block">Subscribers</span>
                <p className="text-lg font-black text-white mt-1">
                  {selectedPkgData.totalCustomers}
                </p>
                <span className="text-[10px] text-cyan-400 font-sans">
                  {selectedPkgData.marketShare}% Market Share
                </span>
              </div>

              <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800">
                <span className="text-[10px] text-slate-400 uppercase font-semibold font-sans block">Monthly Recurring</span>
                <p className="text-lg font-black text-white mt-1">
                  Rs. {selectedPkgData.monthlyDemand.toLocaleString()}
                </p>
                <span className="text-[10px] text-slate-500 font-sans">Gross Demand</span>
              </div>

              <div className="p-3.5 rounded-xl bg-emerald-950/40 border border-emerald-800/80">
                <span className="text-[10px] text-emerald-400 uppercase font-semibold font-sans block">Total Received</span>
                <p className="text-lg font-black text-emerald-300 mt-1">
                  Rs. {selectedPkgData.totalReceived.toLocaleString()}
                </p>
                <span className="text-[10px] text-emerald-400 font-sans">
                  {selectedPkgData.recoveryRate}% Recovery Rate
                </span>
              </div>

              <div className="p-3.5 rounded-xl bg-rose-950/40 border border-rose-800/80">
                <span className="text-[10px] text-rose-400 uppercase font-semibold font-sans block">Total Pending</span>
                <p className="text-lg font-black text-rose-300 mt-1">
                  Rs. {selectedPkgData.totalPending.toLocaleString()}
                </p>
                <span className="text-[10px] text-rose-400 font-sans">Outstanding Recovery</span>
              </div>
            </div>

            {/* Subscriber Roster on this plan */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="font-bold text-white text-sm flex items-center gap-1.5">
                  <Users className="w-4 h-4 text-cyan-400" />
                  Subscribers on this Plan ({selectedPkgData.customers.length})
                </h4>
                <span className="text-[11px] text-slate-400 font-mono">
                  {selectedPkgData.activeCount} Active / {selectedPkgData.suspendedCount} Suspended
                </span>
              </div>

              {selectedPkgData.customers.length === 0 ? (
                <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 text-center text-xs text-slate-400">
                  No customers currently assigned to this package.
                </div>
              ) : (
                <div className="max-h-64 overflow-y-auto rounded-2xl border border-slate-800">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-950 text-slate-400 uppercase text-[10px] sticky top-0">
                      <tr>
                        <th className="px-3 py-2">Customer Name</th>
                        <th className="px-3 py-2">Username</th>
                        <th className="px-3 py-2">Area / Sector</th>
                        <th className="px-3 py-2 text-right">Monthly Fee</th>
                        <th className="px-3 py-2 text-right">Pending Balance</th>
                        <th className="px-3 py-2 text-center">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800 font-mono">
                      {selectedPkgData.customers.map((c) => (
                        <tr key={c.id} className="hover:bg-slate-800/50">
                          <td className="px-3 py-2 text-white font-sans font-medium">{c.name}</td>
                          <td className="px-3 py-2 text-cyan-300">{c.username}</td>
                          <td className="px-3 py-2 font-sans text-slate-300">{c.areaName}</td>
                          <td className="px-3 py-2 text-right text-slate-200">
                            Rs. {(c.totalMonthly || c.monthlyFee).toLocaleString()}
                          </td>
                          <td className="px-3 py-2 text-right text-rose-400 font-bold">
                            Rs. {(c.pendingBalance || 0).toLocaleString()}
                          </td>
                          <td className="px-3 py-2 text-center font-sans">
                            <span
                              className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                                c.status === 'Active'
                                  ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                                  : 'bg-rose-950 text-rose-400 border border-rose-800'
                              }`}
                            >
                              {c.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        </Modal>
      )}

      {/* Add / Edit Package Modal */}
      {isModalOpen && (
        <Modal
          isOpen
          onClose={() => setIsModalOpen(false)}
          title={editingPkg ? 'Edit Internet Package' : 'Create Internet Package'}
        >
          <form onSubmit={handleSave} className="space-y-4 text-xs">
              <div>
                <label htmlFor="package-name" className="block text-slate-300 font-bold mb-1">Package Name *</label>
                <input
                   id="package-name"
                  type="text"
                  required
                  placeholder="e.g. Turbo Fiber 50M"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="speed" className="block text-slate-300 font-bold mb-1">Speed (Mbps) *</label>
                  <input
                     id="speed"
                    type="number"
                    required
                    min={1}
                    value={speedMbps}
                    onChange={(e) => setSpeedMbps(Number(e.target.value))}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400 font-mono"
                  />
                </div>
                <div>
                  <label htmlFor="monthly-tariff" className="block text-slate-300 font-bold mb-1">Monthly Tariff (PKR) *</label>
                  <input
                     id="monthly-tariff"
                    type="number"
                    required
                    min={100}
                    value={price}
                    onChange={(e) => setPrice(Number(e.target.value))}
                    className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400 font-mono"
                  />
                </div>
              </div>

              <div>
                <label htmlFor="medium-connection-type" className="block text-slate-300 font-bold mb-1">Medium / Connection Type</label>
                <select
                   id="medium-connection-type"
                  value={type}
                  onChange={(e) => setType(e.target.value as any)}
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400"
                >
                  <option value="Fiber">Fiber Optics (FTTH)</option>
                  <option value="Wireless">Wireless PTP Radio</option>
                  <option value="Cable">Ethernet Cable</option>
                </select>
              </div>

              <div>
                <label htmlFor="description" className="block text-slate-300 font-bold mb-1">Description</label>
                <textarea
                   id="description"
                  rows={2}
                  value={desc}
                  onChange={(e) => setDesc(e.target.value)}
                  placeholder="Package features, FUP details, etc."
                  className="w-full px-3 py-2 bg-slate-950 border border-slate-700 rounded-xl text-white focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div className="pt-3 border-t border-slate-800 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 font-semibold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-black shadow-lg shadow-cyan-950/40"
                >
                  Save Package
                </button>
              </div>
            </form>
        </Modal>
      )}
    </div>
  );
};
